"use client";

import {
  Bar,
  BarChart,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  Cell,
} from "recharts";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from "@/components/ui/card";

// --- CHART 1: HOURLY ACTIVITY ---
interface HourlyProps {
  data: { hour: string; count: number }[];
}

export function HourlyActivityChart({ data }: HourlyProps) {
  return (
    <Card className="border border-border/50 shadow-sm bg-card rounded-xl">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
          Peak Hours
        </CardTitle>
        <CardDescription className="text-xs">
          Transaction volume by time of day
        </CardDescription>
      </CardHeader>
      <CardContent>
        {/* 🟢 FIX: Wrap ResponsiveContainer in a div with explicit height and min-width */}
        <div className="h-[250px] w-full min-w-0">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data}>
              <XAxis
                dataKey="hour"
                fontSize={10}
                tickLine={false}
                axisLine={false}
                tick={{ fill: "var(--muted-foreground)" }}
              />
              <Tooltip
                cursor={{ fill: "var(--secondary)" }}
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    return (
                      <div className="rounded border border-border bg-popover px-2 py-1 text-xs shadow-sm">
                        <span className="font-bold text-foreground">
                          {payload[0].value}
                        </span>{" "}
                        <span className="text-muted-foreground">sales</span>
                      </div>
                    );
                  }
                  return null;
                }}
              />
              <Bar
                dataKey="count"
                fill="var(--primary)"
                radius={[4, 4, 0, 0]}
                barSize={20}
              >
                {data.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fillOpacity={entry.count > 0 ? 1 : 0.3}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}

// --- CHART 2: TOP WAITERS ---
interface WaiterProps {
  data: { name: string; revenue: number }[];
}

export function TopWaitersChart({ data }: WaiterProps) {
  return (
    <Card className="border border-border/50 shadow-sm bg-card rounded-xl">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium uppercase tracking-wider text-muted-foreground">
          Top Staff
        </CardTitle>
        <CardDescription className="text-xs">
          Revenue generated by waiters
        </CardDescription>
      </CardHeader>
      <CardContent>
        {/* 🟢 FIX: Wrap ResponsiveContainer in a div with explicit height and min-width */}
        <div className="h-[250px] w-full min-w-0">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={data}
              layout="vertical"
              margin={{ left: 0, right: 30 }}
            >
              <XAxis type="number" hide />
              <YAxis
                dataKey="name"
                type="category"
                fontSize={11}
                tickLine={false}
                axisLine={false}
                width={80}
                tick={{ fill: "var(--foreground)" }}
              />
              <Tooltip
                cursor={{ fill: "var(--secondary)" }}
                content={({ active, payload }) => {
                  if (active && payload && payload.length) {
                    return (
                      <div className="rounded border border-border bg-popover px-2 py-1 text-xs shadow-sm">
                        <span className="font-bold text-foreground">
                          ${payload[0].value}
                        </span>
                      </div>
                    );
                  }
                  return null;
                }}
              />
              <Bar
                dataKey="revenue"
                fill="var(--primary)"
                radius={[0, 4, 4, 0]}
                barSize={15}
              >
                {data.map((_, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={
                      index === 0 ? "var(--primary)" : "var(--muted-foreground)"
                    }
                    opacity={index === 0 ? 1 : 0.5}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}
